#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us
  identity:
    hostname: haproxy-build
    username: ubuntu
    password: "$6$rounds=4096$saltsalt$hashed_placeholder"
  ssh:
    install-server: true
    authorized-keys:
      - ${ssh_public_key}
    allow-pw: false
  packages:
    - qemu-guest-agent
  storage:
    layout:
      name: direct
  late-commands:
    - systemctl enable qemu-guest-agent
